# Build EHIPAP Android APK + AAB (Capacitor)
# Prerequisites: Node.js, JDK 21, Android SDK at C:\Android\Sdk

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path $PSScriptRoot -Parent
$Frontend = Join-Path $ProjectRoot "frontend"
$Android = Join-Path $Frontend "android"
$PhoneApkDir = Join-Path $ProjectRoot "phone-apk"
$AndroidEnv = Join-Path $Frontend ".env.android"

$env:JAVA_HOME = "C:\Program Files\Eclipse Adoptium\jdk-21.0.11.10-hotspot"
$env:ANDROID_HOME = "C:\Android\Sdk"
$env:ANDROID_SDK_ROOT = $env:ANDROID_HOME

function Get-LanIPv4 {
    $candidates = Get-NetIPConfiguration |
        Where-Object { $_.IPv4DefaultGateway -and $_.NetAdapter.Status -eq "Up" } |
        ForEach-Object { $_.IPv4Address.IPAddress } |
        Where-Object {
            $_ -and
            $_ -notlike "169.254.*" -and
            $_ -ne "127.0.0.1"
        }

    if (-not $candidates) {
        $candidates = Get-NetIPAddress -AddressFamily IPv4 |
            Where-Object {
                $_.IPAddress -notlike "169.254.*" -and
                $_.IPAddress -ne "127.0.0.1"
            } |
            Select-Object -ExpandProperty IPAddress
    }

    return $candidates | Select-Object -First 1
}

$lanIp = Get-LanIPv4
if (-not $lanIp) {
    Write-Host "ERROR: Could not detect your PC LAN IP. Connect Wi-Fi/Ethernet and try again." -ForegroundColor Red
    exit 1
}

$apiBaseUrl = "http://${lanIp}:8880"
Write-Host "==> Android API URL: $apiBaseUrl" -ForegroundColor Cyan
@"
# Auto-generated by scripts/build-android.ps1 for real-phone testing.
# Rebuild after changing Wi-Fi/network so this points at the backend host.
VITE_API_BASE_URL=$apiBaseUrl
VITE_APP_NAME=EHIPAP
VITE_APP_VERSION=1.0.0
"@ | Set-Content -Path $AndroidEnv -Encoding ASCII

Write-Host "==> Verifying phone-facing backend login..." -ForegroundColor Cyan
$loginBody = @{ username = "hrmanager"; password = "HRManager@123" } | ConvertTo-Json
try {
    $login = Invoke-RestMethod -Method Post -Uri "$apiBaseUrl/api/v1/auth/login" -ContentType "application/json" -Body $loginBody -TimeoutSec 10
    Write-Host "    Login OK as $($login.user.username)" -ForegroundColor Green
} catch {
    Write-Host ""
    Write-Host "ERROR: Phone-facing login failed at $apiBaseUrl/api/v1/auth/login" -ForegroundColor Red
    Write-Host "Start backend first: .\scripts\start-all.ps1" -ForegroundColor Yellow
    Write-Host "Also ensure phone and PC are on the same Wi-Fi/hotspot, then rebuild." -ForegroundColor Yellow
    Write-Host $_.Exception.Message -ForegroundColor DarkGray
    exit 1
}

Write-Host "==> Building React app for Android..." -ForegroundColor Cyan
Push-Location $Frontend
npm run build:android
if ($LASTEXITCODE -ne 0) { Pop-Location; exit 1 }

Write-Host "==> Syncing Capacitor..." -ForegroundColor Cyan
npx cap sync android
if ($LASTEXITCODE -ne 0) { Pop-Location; exit 1 }
Pop-Location

Write-Host "==> Building APK + AAB..." -ForegroundColor Cyan
Push-Location $Android
.\gradlew.bat assembleDebug assembleRelease bundleRelease
$code = $LASTEXITCODE
Pop-Location

if ($code -ne 0) { exit $code }

$debugApk = Join-Path $Android "app\build\outputs\apk\debug\app-debug.apk"
$releaseApk = Join-Path $Android "app\build\outputs\apk\release\app-release.apk"
$releaseAab = Join-Path $Android "app\build\outputs\bundle\release\app-release.aab"

if (-not (Test-Path $PhoneApkDir)) { New-Item -ItemType Directory -Path $PhoneApkDir | Out-Null }
Copy-Item -LiteralPath $debugApk -Destination (Join-Path $PhoneApkDir "EHIPAP.apk") -Force

Write-Host ""
Write-Host "BUILD SUCCESSFUL" -ForegroundColor Green
Write-Host "Debug APK:   $debugApk"
Write-Host "Phone APK:   $PhoneApkDir\EHIPAP.apk"
Write-Host "Release APK: $releaseApk"
Write-Host "Release AAB: $releaseAab"
Write-Host ""
Write-Host "Install this fresh APK on your phone: phone-apk\EHIPAP.apk"
Write-Host "Backend used by APK: $apiBaseUrl"
